title: Merge Hell Team
subtitle: Coding is smooth, integration is not
slug: merge-hell-team
stages:
  - name: Development
    queue: 2
    ct: 2d
  - name: Merge
    queue: 15
    ct: 9.6h
  - name: Integration
    queue: 3
    ct: 8h
